Student Name: Gaurab Chhetri

Student Number: 2358549

# **1) TO - DO - Task**

**1.1) Exercise on Functions:**

Task - 1:
Create a Python program that converts between different units of measurement.

• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.

• Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def convert_units():
    """Converts between different units of measurement."""
    print("Choose conversion type:")
    print("1. Length (m <-> ft)")
    print("2. Weight (kg <-> lbs)")
    print("3. Volume (L <-> gal)")

    conversion_type = input("Enter 1, 2, or 3: ")

    try:
        if conversion_type == "1":
            amount = float(input("Enter value: "))
            unit_type = input("Enter unit (m/ft): ").lower()
            if unit_type == "m":
                print(f"{amount} meters = {amount * 3.28084} feet")
            elif unit_type == "ft":
                print(f"{amount} feet = {amount / 3.28084} meters")
            else:
                print("Invalid unit.")
        elif conversion_type == "2":
            amount = float(input("Enter value: "))
            unit_type = input("Enter unit (kg/lbs): ").lower()
            if unit_type == "kg":
                print(f"{amount} kg = {amount * 2.20462} lbs")
            elif unit_type == "lbs":
                print(f"{amount} lbs = {amount / 2.20462} kg")
            else:
                print("Invalid unit.")
        elif conversion_type == "3":
            amount = float(input("Enter value: "))
            unit_type = input("Enter unit (L/gal): ").lower()
            if unit_type == "l":
                print(f"{amount} liters = {amount * 0.264172} gallons")
            elif unit_type == "gal":
                print(f"{amount} gallons = {amount / 0.264172} liters")
            else:
                print("Invalid unit.")
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Please enter a number.")

convert_units()


Choose conversion type:
1. Length (m <-> ft)
2. Weight (kg <-> lbs)
3. Volume (L <-> gal)
Enter 1, 2, or 3: 3
Enter value: 4
Enter unit (L/gal): gal
4.0 gallons = 15.141650137031933 liters


Task - 2:
Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).
3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.

• Requirements:
1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def perform_operation():
    """Performs various mathematical operations on a list of numbers."""
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    operation_choice = input("Enter 1, 2, 3, or 4: ")

    try:
        num_list = list(map(float, input("Enter numbers separated by spaces: ").split()))
        if not num_list:
            print("List cannot be empty.")
            return

        if operation_choice == "1":
            print(f"Sum: {sum(num_list)}")
        elif operation_choice == "2":
            print(f"Average: {sum(num_list) / len(num_list)}")
        elif operation_choice == "3":
            print(f"Maximum: {max(num_list)}")
        elif operation_choice == "4":
            print(f"Minimum: {min(num_list)}")
        else:
            print("Invalid choice.")
    except ValueError:
        print("Invalid input. Please enter numbers.")

perform_operation()


Choose an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter 1, 2, 3, or 4: 1
Enter numbers separated by spaces: 3
Sum: 3.0


**1.2) Exercise on List Manipulation:**

1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract every other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_alternate_elements(data_list):
    """Returns a new list containing every other element from the original list."""
    return data_list[::2]

print(extract_alternate_elements([1, 2, 3, 4, 5, 6]))


[1, 3, 5]


2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:

– Define a function get sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def get_slice(data_list, start_index, end_index):
    """Returns a sublist from start index to end index (inclusive)."""
    return data_list[start_index:end_index+1]

print(get_slice([1, 2, 3, 4, 5, 6], 2, 4))


[3, 4, 5]


3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse list(lst) that takes a list lst and returns a reversed list using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
def reverse_sequence(data_sequence):
    """Returns the reversed list using slicing."""
    return data_sequence[::-1]

print(reverse_sequence([1, 2, 3, 4, 5]))


[5, 4, 3, 2, 1]


4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:

– Define a function remove first last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def trim_edges(data_list):
    """Removes the first and last elements from the list."""
    return data_list[1:-1]

print(trim_edges([1, 2, 3, 4, 5]))


[2, 3, 4]


5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get first n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_elements(data_list, count):
    """Returns the first 'count' elements of the list."""
    return data_list[:count]

print(get_first_elements([1, 2, 3, 4, 5], 3))


[1, 2, 3]


6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get last n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_elements(data_list, count):
    """Returns the last 'count' elements of the list."""
    return data_list[-count:]

print(get_last_elements([1, 2, 3, 4, 5], 2))


[4, 5]


7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last element and skipping one element in between.

• Requirements:

– Define a function reverse skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_alternate(data_list):
    """Returns every second element from the end, moving backward."""
    return data_list[-2::-2]

print(reverse_alternate([1, 2, 3, 4, 5, 6]))


[5, 3, 1]


**1.3) Exercise on Nested List:**

1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(nested_data):
    """Flattens a nested list into a single list."""
    flat_result = []
    for element in nested_data:
        if isinstance(element, list):
            flat_result.extend(flatten(element))
        else:
            flat_result.append(element)
    return flat_result

nested_list = [[1, 2], [3, 4], [5]]
print(flatten(nested_list))


[1, 2, 3, 4, 5]


2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access nested element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1, 2], the output should be 6.

In [ ]:
def access_nested_value(nested_data, index_list):
    """Extracts a specific element from a nested list given its indices."""
    value = nested_data
    for idx in index_list:
        value = value[idx]
    return value

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
index_path = [1, 2]
print(access_nested_value(nested_list, index_path))


6


3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(nested_data):
    """Calculates the sum of all numbers in a nested list."""
    total_sum = 0
    for element in nested_data:
        if isinstance(element, list):
            total_sum += sum_nested(element)
        else:
            total_sum += element
    return total_sum

nested_list = [[1, 2], [3, [4, 5]], 6]
print(sum_nested(nested_list))


21


4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove element(lst, elem) that removes elem from lst and returns the modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should be [[1], [3], [4, 5]].

In [ ]:
def remove_value(nested_data, target_value):
    """Removes all occurrences of a specific element from a nested list."""
    filtered_result = []
    for element in nested_data:
        if isinstance(element, list):
            filtered_result.append(remove_value(element, target_value))
        elif element != target_value:
            filtered_result.append(element)
    return filtered_result

nested_list = [[1, 2], [3, 2], [4, 5]]
value_to_remove = 2
print(remove_value(nested_list, value_to_remove))


[[1], [3], [4, 5]]


5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find max(lst) that takes a nested list lst and returns the maximum element.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(nested_data):
    """Finds the maximum element in a nested list."""
    highest_value = float('-inf')
    for element in nested_data:
        if isinstance(element, list):
            highest_value = max(highest_value, find_max(element))
        else:
            highest_value = max(highest_value, element)
    return highest_value

nested_list = [[1, 2], [3, [4, 5]], 6]
print(find_max(nested_list))


6


6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:

– Define a function count occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should be 3.

In [ ]:
def count_occurrences(nested_data, target_value):
    """Counts how many times a specific element appears in a nested list."""
    occurrence_count = 0
    for element in nested_data:
        if isinstance(element, list):
            occurrence_count += count_occurrences(element, target_value)
        elif element == target_value:
            occurrence_count += 1
    return occurrence_count

nested_list = [[1, 2], [2, 3], [2, 4]]
value_to_count = 2
print(count_occurrences(nested_list, value_to_count))


3


7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(nested_data):
    """Flattens a list of lists of lists into a single list."""
    flattened_result = []
    for element in nested_data:
        if isinstance(element, list):
            flattened_result.extend(deep_flatten(element))
        else:
            flattened_result.append(element)
    return flattened_result

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
print(deep_flatten(nested_list))


[1, 2, 3, 4, 5, 6, 7, 8]


8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average nested(lst) that takes a nested list lst and returns the average of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(nested_data):
    """Calculates the average of all elements in a nested list."""
    flattened_list = deep_flatten(nested_data)
    return sum(flattened_list) / len(flattened_list) if flattened_list else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
print(average_nested(nested_list))


3.5


**1.4) To - Do - NumPy**

1.4.1) Basic Vector and Matrix Operation with Numpy.

Problem - 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
# 1. Initialize an empty array with size 2x2.
import numpy as np
matrix_empty = np.empty((2, 2))
print(matrix_empty)


[[2.99231664e-316 0.00000000e+000]
 [6.59737730e-310 6.67421148e-310]]


In [ ]:
# 2. Initialize an all-ones array with size 4x2.
import numpy as np
matrix_ones = np.ones((4, 2))
print(matrix_ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
# 3. Return a new array of given shape and type, filled with a specified value.
import numpy as np
matrix_filled = np.full((3, 3), 7)
print(matrix_filled)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [ ]:
# 4. Return a new array of zeros with the same shape and type as a given array.
import numpy as np
original_matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix_zeros = np.zeros_like(original_matrix)
print(matrix_zeros)


[[0 0 0]
 [0 0 0]]


In [ ]:
# 5. Return a new array of ones with the same shape and type as a given array.
import numpy as np
original_matrix = np.array([[1, 2, 3], [4, 5, 6]])
matrix_ones = np.ones_like(original_matrix)
print(matrix_ones)


[[1 1 1]
 [1 1 1]]


In [ ]:
# 6. Convert an existing list to a NumPy array.
import numpy as np
list_numbers = [1, 2, 3, 4]
array_numpy = np.array(list_numbers)
print(array_numpy)


[1 2 3 4]


Problem - 2:

Array Manipulation: Numerical Ranges and Array indexing

Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# 1. Create an array with values ranging from 10 to 49.
import numpy as np
range_array = np.arange(10, 50)
print(range_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
# 2. Create a 3x3 matrix with values ranging from 0 to 8.
import numpy as np
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 3. Create a 3x3 identity matrix.
import numpy as np
matrix_identity = np.eye(3)
print(matrix_identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 4. Create a random array of size 30 and find the mean of the array.
import numpy as np
array_random = np.random.random(30)
mean_random = array_random.mean()
print(mean_random)


0.5247469017348465


In [ ]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
matrix_random = np.random.random((10, 10))
min_random = matrix_random.min()
max_random = matrix_random.max()
print(f"Min value = {min_random}")
print(f"Max value = {max_random}")


Min value = 0.005770946074363126
Max value = 0.9902879161420265


In [ ]:
# 6. Create a zero array of size 10 and replace the 5th element with 1.
import numpy as np
array_zeros = np.zeros(10)
array_zeros[4] = 1
print(array_zeros)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 7. Reverse an array.
import numpy as np
array_numbers = np.array([1, 2, 0, 0, 4, 0])
array_reversed = array_numbers[::-1]
print(array_reversed)


[0 4 0 0 2 1]


In [ ]:
# 8. Create a 2D array with 1 on the border and 0 inside.
import numpy as np
matrix_border = np.ones((5, 5))
matrix_border[1:-1, 1:-1] = 0
print(matrix_border)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 9. Create an 8x8 matrix and fill it with a checkerboard pattern.
import numpy as np

matrix_checkerboard = np.zeros((8, 8), dtype=int)
matrix_checkerboard[1::2, ::2] = 1
matrix_checkerboard[::2, 1::2] = 1

print(matrix_checkerboard)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3:

Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column. {Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
# 1. Add two arrays.
import numpy as np

array_one =  np.array([9,10])
array_two = np.array([11,12])
array_sum = array_one + array_two

print(array_sum)


[20 22]


In [ ]:
# 2. Subtract two arrays.
import numpy as np

array_one =  np.array([9,10])
array_two = np.array([11,12])
array_difference = array_one - array_two

print(array_difference)


[-2 -2]


In [ ]:
# 3. Multiply the array with any integer of your choice.
import numpy as np

array_matrix = np.array([[1, 2], [3, 5]])
multiplied_matrix = array_matrix * 4

print(multiplied_matrix)


[[ 4  8]
 [12 20]]


In [ ]:
# 4. Find the square of each element of the array.
import numpy as np

array_matrix = np.array([[5,6],[7,8]])
squared_matrix = array_matrix ** 2

print(squared_matrix)


[[25 36]
 [49 64]]


In [ ]:
# 5. Find the dot product between: vector_one and vector_two; matrix_one and vector_one; matrix_one and matrix_two.
import numpy as np

matrix_one = np.array([[1, 2], [3, 5]])
matrix_two = np.array([[5, 6], [7, 8]])
vector_one = np.array([9, 10])
vector_two = np.array([11, 12])

dot_vector = np.dot(vector_one, vector_two)
dot_matrix_vector = np.dot(matrix_one, vector_one)
dot_matrices = np.dot(matrix_one, matrix_two)


print(f"Dot product of matrix_one and matrix_two = {dot_matrices}")
print(f"Dot product of matrix_one and vector_one = {dot_matrix_vector}")
print(f"Dot product of vector_one and vector_two = {dot_vector}")


Dot product of matrix_one and matrix_two = [[19 22]
 [50 58]]
Dot product of matrix_one and vector_one = [29 77]
Dot product of vector_one and vector_two = 219


In [ ]:
# 6. Concatenate matrix_x and matrix_y along rows and vector_a and vector_b along columns.
import numpy as np

matrix_x = np.array([[1, 2], [3, 5]])
matrix_y = np.array([[5, 6], [7, 8]])
vector_a = np.array([9, 10])
vector_b = np.array([11, 12])

concatenated_matrices = np.concatenate((matrix_x, matrix_y), axis=0)

vector_a = vector_a.reshape(-1, 1)
vector_b = vector_b.reshape(-1, 1)

concatenated_vectors = np.concatenate((vector_a, vector_b), axis=1)

print("Concatenation of matrix_x and matrix_y along rows:\n", concatenated_matrices)
print("\nConcatenation of vector_a and vector_b along columns:\n", concatenated_vectors)


Concatenation of matrix_x and matrix_y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenation of vector_a and vector_b along columns:
 [[ 9 11]
 [10 12]]


In [ ]:
# 7. Concatenate matrix_A and vector_B; if you get an error, observe and explain why.
import numpy as np

matrix_A = np.array([[1, 2], [3, 5]])
vector_B = np.array([9, 10])

try:
    concatenated_result = np.concatenate((matrix_A, vector_B), axis=0)
    print("Concatenation successful:\n", concatenated_result)
except ValueError as error_message:
    print("Error:", error_message)


Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Explanation:

The shape of x is (2,2) (a 2×2 matrix).
The shape of v is (2,) (a 1D array with 2 elements).
When concatenating along axis=0 (rows), NumPy expects the number of columns to match. x has 2 columns, but v has no explicit column dimension (it's 1D), causing a shape mismatch.

Problem - 4:

Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1

x − y + 2z = −3

3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# 1. Prove A.A^−1 = I.
import numpy as np

A = np.array([[3, 4], [7, 8]])

A_inv = np.linalg.inv(A)

identity_matrix = np.dot(A, A_inv)

print("A inverse (A⁻¹):\n", A_inv)
print("\nA * A⁻¹:\n", identity_matrix)

I = np.eye(2)
is_identity = np.allclose(identity_matrix, I)

print("\nIs A * A⁻¹ equal to Identity matrix?:", is_identity)


A inverse (A⁻¹):
 [[-2.    1.  ]
 [ 1.75 -0.75]]

A * A⁻¹:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

Is A * A⁻¹ equal to Identity matrix?: True


In [ ]:
# 2. Prove AB ̸= BA.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("AB:\n", AB)
print("\nBA:\n", BA)

is_equal = np.array_equal(AB, BA)

print("\nIs AB equal to BA?:", is_equal)


AB:
 [[23 13]
 [51 29]]

BA:
 [[36 44]
 [13 16]]

Is AB equal to BA?: False


In [ ]:
# 3. Prove (AB)^T = B^T A^T.
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# Compute AB
AB = np.dot(A, B)

# Compute (AB)^T
transpose_AB = AB.T

# Compute B^T and A^T
B_T = B.T
A_T = A.T

# Compute B^T A^T
BT_AT = np.dot(B_T, A_T)

print("Transpose of AB ( (AB)^T ):\n", transpose_AB)
print("\nMultiplication of Transposed Matrices ( B^T A^T ):\n", BT_AT)

# Verify if (AB)^T == B^T A^T
is_equal = np.array_equal(transpose_AB, BT_AT)
print("\nIs (AB)^T equal to B^T A^T?:", is_equal)

Transpose of AB ( (AB)^T ):
 [[23 51]
 [13 29]]

Multiplication of Transposed Matrices ( B^T A^T ):
 [[23 51]
 [13 29]]

Is (AB)^T equal to B^T A^T?: True


In [ ]:
# Solve the following system of Linear equation using Inverse Methods.
# 2x − 3y + z = −1
# x − y + 2z = −3
# 3x + y − z = 9

import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution for x, y, z:")
print(f"x = {X[0]:.2f}")
print(f"y = {X[1]:.2f}")
print(f"z = {X[2]:.2f}")

Solution for x, y, z:
x = 2.00
y = 1.00
z = -2.00


In [ ]:
# Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function of Numpy}
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)

X = np.dot(A_inv, B)

print("Solution using np.linalg.inv():")
print(f"x = {X[0]:.2f}")
print(f"y = {X[1]:.2f}")
print(f"z = {X[2]:.2f}")

Solution using np.linalg.inv():
x = 2.00
y = 1.00
z = -2.00


Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
#Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000.
import time
import random

# Define the size of the lists
size = 1_000_000

# Generate two lists with random integers
list1 = [random.randint(0, 100) for _ in range(size)]
list2 = [random.randint(0, 100) for _ in range(size)]

# Measure the time taken for element-wise addition using list comprehension
start_time = time.time()

result = [a + b for a, b in zip(list1, list2)]

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise addition using Python lists: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using Python lists: 0.045571 seconds


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the arrays
size = 1_000_000

# Generate two NumPy arrays with random integers
array1 = np.random.randint(0, 100, size)
array2 = np.random.randint(0, 100, size)

# Measure the time taken for element-wise addition using NumPy
start_time = time.time()

result_array = array1 + array2  # Vectorized operation

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise addition using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken for element-wise addition using NumPy arrays: 0.008701 seconds


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
#Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time
import random

# Define the size of the lists
size = 1_000_000

# Generate two lists with random integers
list1 = [random.randint(0, 100) for _ in range(size)]
list2 = [random.randint(0, 100) for _ in range(size)]

# Measure the time taken for element-wise multiplication using list comprehension
start_time = time.time()

result = [a * b for a, b in zip(list1, list2)]  # Multiplication operation

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise multiplication using Python lists: {end_time - start_time:.6f} seconds")


Time taken for element-wise multiplication using Python lists: 0.079108 seconds


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the arrays
size = 1_000_000

# Generate two NumPy arrays with random integers
array1 = np.random.randint(0, 100, size)
array2 = np.random.randint(0, 100, size)

# Measure the time taken for element-wise multiplication using NumPy
start_time = time.time()

result_array = array1 * array2  # Vectorized multiplication

end_time = time.time()

# Print the time taken
print(f"Time taken for element-wise multiplication using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken for element-wise multiplication using NumPy arrays: 0.014213 seconds


3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
# Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and Print the time taken for this operation.
import time
import random

# Define the size of the lists
size = 1_000_000

# Generate two lists with random integers
list1 = [random.randint(0, 100) for _ in range(size)]
list2 = [random.randint(0, 100) for _ in range(size)]

# Measure the time taken for computing the dot product using Python lists
start_time = time.time()

dot_product = sum(a * b for a, b in zip(list1, list2))  # Manual dot product calculation

end_time = time.time()

# Print the time taken
print(f"Time taken for dot product using Python lists: {end_time - start_time:.6f} seconds")


Time taken for dot product using Python lists: 0.148694 seconds


In [ ]:
#Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the arrays
size = 1_000_000

# Generate two NumPy arrays with random integers
array1 = np.random.randint(0, 100, size)
array2 = np.random.randint(0, 100, size)

# Measure the time taken for computing the dot product using NumPy
start_time = time.time()

dot_product = np.dot(array1, array2)  # Optimized dot product calculation

end_time = time.time()

# Print the time taken
print(f"Time taken for dot product using NumPy arrays: {end_time - start_time:.6f} seconds")


Time taken for dot product using NumPy arrays: 0.002659 seconds


Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
#Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea- sure and print the time taken for this operation.

import time
import random

# Define the size of the matrices
size = 1000

# Generate two 1000x1000 matrices with random integers
matrix1 = [[random.randint(0, 100) for _ in range(size)] for _ in range(size)]
matrix2 = [[random.randint(0, 100) for _ in range(size)] for _ in range(size)]

# Initialize the result matrix with zeros
result = [[0] * size for _ in range(size)]

# Measure the time taken for matrix multiplication using nested loops
start_time = time.time()

for i in range(size):
    for j in range(size):
        for k in range(size):
            result[i][j] += matrix1[i][k] * matrix2[k][j]

end_time = time.time()

# Print the time taken
print(f"Time taken for matrix multiplication using Python lists: {end_time - start_time:.6f} seconds")


Time taken for matrix multiplication using Python lists: 318.571554 seconds


In [ ]:
#Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.
import time
import numpy as np

# Define the size of the matrices
size = 1000

# Generate two 1000x1000 matrices with random integers using NumPy
matrix1 = np.random.randint(0, 100, (size, size))
matrix2 = np.random.randint(0, 100, (size, size))

# Measure the time taken for matrix multiplication using NumPy
start_time = time.time()

# Matrix multiplication using NumPy's dot product function
result = np.dot(matrix1, matrix2)

end_time = time.time()

# Print the time taken
print(f"Time taken for matrix multiplication using NumPy: {end_time - start_time:.6f} seconds")


Time taken for matrix multiplication using NumPy: 4.741620 seconds
